version: "3.8"

services:
  mediareaparr:
    image: snwaine/mediareaparr:latest
    container_name: mediareaparr
    restart: unless-stopped

    environment:
      TZ: Europe/London
      CONFIG_DIR: /config
      LOG_PATH: /config/mediareaparr.log
      HTTP_TIMEOUT_SECONDS: 30

    volumes:
      - /mnt/user/appdata/mediareaparr:/config

    ports:
      - "7676:7676"

    command: ["python3", "/app/webui.py"]
